export const DATA = [
  {
    name: "Irbid",
    areas: ["Irbid City", "Ar Ramtha", "Bani Kinana"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4", "5", "6+"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished", "d"],
    floor: [
      "Ground Floor",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
    buildingages: [
      "0 - 11 months",
      "1 - 5 Years",
      "6 -9 Years",
      "10 - 19 Years",
      "20+ Years",
    ],
    Rent_period: ["Daily", "Weekly", "Monthly", "Yearly"],
    keyFeatures: [
      "Balcony",
      "Pool",
      "Gym",
      "Parking",
      "Security",
      "Pet Friendly",
      "Elevator",
      "Garden",
      "Rooftop Access",
      "High-Speed Internet",
      "Modern Appliances",
      "Air Conditioning",
      "Furnished",
      "Waterfront View",
      "Near Public Transport",
    ],
    additionalBenefits: [
      "Elevator",
      "Garden",

      "Staircase",
      "24/7 Security",
      "Children's Play Area",
      "Fire Safety",
      "Spa Facilities",
      "Sports Facilities",
      "Guest Parking",
      "CCTV Surveillance",
      "Backup Generator",
      "Laundry Room",
      "Storage Space",
      "Waste Disposal System",
    ],
    nearbyLocations: [
      "Restaurants",
      "Schools",
      "Supermarkets",
      "Malls",
      "Hospitals",
      "Parks",
      "Gyms",
      "Banks",
      "Pharmacies",
      "Cinemas",
      "Public Transport Stations",
      "Libraries",
      "Post Offices",
      "Police Stations",
      "Universities",
    ],
    orientations: [
      "North",
      "South",
      "East",
      "West",
      "Northeast",
      "Northwest",
      "Southeast",
      "Southwest",
    ],
  },
  {
    name: "Ajloun",
    areas: ["Ajloun City", "Kufranjah", "Anjara"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished"],
    floor: [
      "Ground Floor",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
  },
  {
    name: "Jerash",
    areas: ["Jerash City", "Souf", "Musha"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished"],
    floor: [
      "Ground Floor",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
  },
  {
    name: "Mafraq",
    areas: ["Mafraq City", "Al-Sareeh", "Umm el-Jimal"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished"],
    floor: [
      "Ground Floor",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
  },
  {
    name: "Balqa",
    areas: ["Salt City", "Ain Al Basha", "Fuheis"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished"],
  },
  {
    name: "Amman",
    areas: ["Amman City", "Wadi As-Seer", "Al-Jubaiha"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished"],
    floor: [
      "Ground Floor",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
  },
  {
    name: "Zarqa",
    areas: ["Zarqa City", "Russeifa", "Azraq"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished"],
    floor: [
      "Ground Floor",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
  },
  {
    name: "Madaba",
    areas: ["Madaba City", "Ma'in", "Libb"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished"],
    floor: [
      "Ground Floor",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
  },
  {
    name: "Karak",
    areas: ["Al-Karak City", "Al-Mazar", "ahmed", "Mohammed"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished"],
    floor: [
      "Ground Floor",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
  },
  {
    name: "Tafilah",
    areas: ["Tafilah City", "Busaira", "Qadisiyah"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished"],
    floor: [
      "Ground Floor",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
  },
  {
    name: "Ma'an",
    areas: ["Ma'an City", "Shobak", "Petra"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished"],
    floor: [
      "Ground Floor",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
    buildingages: [
      "0 - 11 months",
      "1 - 5 Years",
      "6 -9 Years",
      "10 - 19 Years",
      "20+ Years",
    ],
  },
  {
    name: "Aqaba",
    areas: ["Aqaba City", "Al-Quwairah", "Wadi Rum"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished"],
    floor: [
      "Ground Floor",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
  },
];
