export const DATA = [
  {
    name: "Irbid",
    areas: ["Irbid City", "Ar Ramtha", "Bani Kinana"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4", "5", "6+"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished", "d"],
    floor: [
      "Ground Floor",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
    buildingages: [
      "0 - 11 months",
      "1 - 5 Years",
      "6 -9 Years",
      "10 - 19 Years",
      "20+ Years",
    ],
    Rent_period: ["Daily", "Weekly", "Monthly", "Yearly"],
    keyFeatures: [
      "Balcony",
      "Pool",
      "Gym",
      "Parking",
      "Security",
      "Pet Friendly",
      "Elevator",
      "Garden",
      "Rooftop Access",
      "High-Speed Internet",
      "Modern Appliances",
      "Air Conditioning",
      "Furnished",
      "Waterfront View",
      "Near Public Transport",
    ],
    additionalBenefits: [
      "Elevator",
      "Garden",

      "Staircase",
      "24/7 Security",
      "Children's Play Area",
      "Fire Safety",
      "Spa Facilities",
      "Sports Facilities",
      "Guest Parking",
      "CCTV Surveillance",
      "Backup Generator",
      "Laundry Room",
      "Storage Space",
      "Waste Disposal System",
    ],
    nearbyLocations: [
      "Restaurants",
      "Schools",
      "Supermarkets",
      "Malls",
      "Hospitals",
      "Parks",
      "Gyms",
      "Banks",
      "Pharmacies",
      "Cinemas",
      "Public Transport Stations",
      "Libraries",
      "Post Offices",
      "Police Stations",
      "Universities",
    ],
    orientations: [
      "North",
      "South",
      "East",
      "West",
      "Northeast",
      "Northwest",
      "Southeast",
      "Southwest",
    ],
  },
  {
    name: "Ajloun",
    areas: ["Ajloun City", "Kufranjah", "Anjara"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished"],
    floor: [
      "Ground Floor",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
  },
  {
    name: "Jerash",
    areas: ["Jerash City", "Souf", "Musha"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished"],
    floor: [
      "Ground Floor",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
  },
  {
    name: "Mafraq",
    areas: ["Mafraq City", "Al-Sareeh", "Umm el-Jimal"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished"],
    floor: [
      "Ground Floor",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
  },
  {
    name: "Balqa",
    areas: ["Salt City", "Ain Al Basha", "Fuheis"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished"],
  },
  {
    name: "Amman",
    areas: ["Amman City", "Wadi As-Seer", "Al-Jubaiha"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished"],
    floor: [
      "Ground Floor",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
  },
  {
    name: "Zarqa",
    areas: ["Zarqa City", "Russeifa", "Azraq"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished"],
    floor: [
      "Ground Floor",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
  },
  {
    name: "Madaba",
    areas: ["Madaba City", "Ma'in", "Libb"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished"],
    floor: [
      "Ground Floor",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
  },
  {
    name: "Karak",
    areas: ["Al-Karak City", "Al-Mazar", "ahmed", "Mohammed"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished"],
    floor: [
      "Ground Floor",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
  },
  {
    name: "Tafilah",
    areas: ["Tafilah City", "Busaira", "Qadisiyah"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished"],
    floor: [
      "Ground Floor",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
  },
  {
    name: "Ma'an",
    areas: ["Ma'an City", "Shobak", "Petra"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished"],
    floor: [
      "Ground Floor",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
    buildingages: [
      "0 - 11 months",
      "1 - 5 Years",
      "6 -9 Years",
      "10 - 19 Years",
      "20+ Years",
    ],
  },
  {
    name: "Aqaba",
    areas: ["Aqaba City", "Al-Quwairah", "Wadi Rum"],
    rooms: ["1", "2", "3", "4", "5", "6+"],
    bathrooms: ["1", "2", "3", "4"],
    roomstate: ["Furnished", "Unfurnished", "Partially Furnished"],
    floor: [
      "Ground Floor",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
  },
];

const provinces = [
  { label: "Amman", value: "1" },
  { label: "Zarqa", value: "2" },
  { label: "Irbid", value: "3" },
  { label: "Aqaba", value: "4" },
  { label: "Mafraq", value: "5" },
  { label: "Ajloun", value: "6" },
  { label: "Jarash", value: "7" },
  { label: "Madaba", value: "8" },
  { label: "Karak", value: "9" },
  { label: "Tafilah", value: "10" },
  { label: "Ma'an", value: "11" },
  { label: "Balqa", value: "12" },
];

const regions = {
  1: [
    { label: "Jabal Amman", value: "1-1" },
    { label: "Abdoun", value: "1-2" },
    { label: "Sweifieh", value: "1-3" },
    { label: "Khalda", value: "1-4" },
    { label: "Tla' Al-Ali", value: "1-5" },
    { label: "Dabouq", value: "1-6" },
    { label: "Abu nusseir", value: "1-7" },
    { label: "Tabrbour", value: "1-8" },
    { label: "Down Town", value: "1-9" },
    { label: "Jabal Al-Hussein", value: "1-10" },
    { label: "Shmesani", value: "1-11" },
    { label: "Al-Jubaiha", value: "1-12" },
    { label: "Al-Hashmi", value: "1-13" },
    { label: "Marka", value: "1-14" },
    { label: "Jabal Al-Hussein", value: "1-10" },
    

  ],
  2: [
    { label: "Downtown Zarqa (Al-Balad)", value: "1-1" },
    { label: "Al-Majdiya", value: "2-1" },
    { label: "Al-Hashmi", value: "2-2" },
    { label: "Al-Ghweirieh", value: "2-3" },
    { label: "Al-Ruseifa", value: "2-4" },
    { label: "Al-Zawahreh", value: "2-5" },
    { label: "New Zarqa (Zarqa Al-Jadida)", value: "2-6" },
    { label: "Prince Faisal", value: "2-7" },
    { label: "Al-Manshiya", value: "2-8" },
    { label: "Al-Dheibat", value: "2-9" },
    { label: "Zarqa Free Zone", value: "2-10" },
    { label: "Al-Hashemi Industrial Area", value: "2-11" },
  ],
  3: [
    { label: "Downtown Irbid (Al-Balad)", value: "3-1" },
    { label: "Al-Husun", value: "3-2" },
    { label: "Al-Nasr", value: "3-3" },
    { label: "Al-Mashari'a", value: "3-4" },
    { label: "Al-Tal", value: "3-5" },
    { label: "Al-Ramtha", value: "3-6" },
    { label: "Al-Sarih", value: "3-7" },
    { label: "Hakama", value: "3-8" },
    { label: "Bayt Ras", value: "3-9" },
    { label: "Al-Hijazeen", value: "3-10" },
    { label: "Al-Mazraa", value: "3-11" },
    { label: "Al-Shajara", value: "3-12" },
    { label: "Irbid Camp", value: "3-13" }
  ],
  4: [
    { label: "Aqaba City", value: "4-1" },
    { label: "Al-Quwayrah", value: "4-2" },
  ],
  5: [
    { label: "Mafraq City", value: "5-1" },
    { label: "Khalidiya", value: "5-2" },
  ],
  6: [
    { label: "Ajloun City", value: "6-1" },
    { label: "Anjara", value: "6-2" },
  ],
  7: [
    { label: "Jarash City", value: "7-1" },
    { label: "Sakib", value: "7-2" },
  ],
  8: [
    { label: "Madaba City", value: "8-1" },
    { label: "Ma'in", value: "8-2" },
  ],
  9: [
    { label: "Karak City", value: "9-1" },
    { label: "Mazar", value: "9-2" },
  ],
  10: [
    { label: "Tafilah City", value: "10-1" },
    { label: "Busrra", value: "10-2" },
  ],
  11: [
    { label: "Downtown Ma'an (Al-Balad)", value: "11-1" },
    { label: "Al-Shamiya", value: "11-2" },
    { label: "Al-Jafr", value: "11-3" },
    { label: "Al-Manshiyah", value: "11-4" },
    { label: "Al-Tafilah", value: "11-5" },
    { label: "Al-Hussein", value: "11-6" },
    { label: "Al-Qadissiya", value: "11-7" },
    { label: "Al-Mudawara", value: "11-8" },
    { label: "Wadi Musa", value: "11-9" },
    { label: "Shoubak", value: "11-10" },
    { label: "Al-Taybeh", value: "11-11" }
  ],
  12: [
    { label: "Salt City", value: "12-1" },
    { label: "Al-Sukhnah", value: "12-2" },
    { label: "Al-Azraq", value: "12-3" },
    { label: "Al-Hashimiya", value: "12-4" },
    { label: "Wadi Shuaib", value: "12-5" },
    { label: "Ain Al-Basha", value: "12-6" },
    { label: "Al-Quwaysimah", value: "12-7" },
    { label: "Dair Alla", value: "12-8" },
    { label: "Mahis", value: "12-9" },
    { label: "Deir Yassin", value: "12-10" },
    { label: "Thiban", value: "12-11" }
  ],
};

const propertyFeatures = [
  { label: "Elevator", value: "1" },
  { label: "Parking", value: "2" },
  { label: "Gym", value: "3" },
  { label: "Pool", value: "4" },
  { label: "Garden", value: "5" },
  { label: "Security", value: "6" },
  { label: "Playground", value: "7" },
  { label: "Wi-Fi", value: "8" },
];

const nearbyLocations = [
  { label: "School", value: "1" },
  { label: "Hospital", value: "2" },
  { label: "Mall", value: "3" },
  { label: "Park", value: "4" },
  { label: "Restaurant", value: "5" },
];

const lessons = [
  {
    name: "Apartments for Rent",
    name2: "Home for rent",
  },
  {
    name: "Apartments for sale",
    name2: "Home for sale",
  },
  {
    name: "Hotel apartments and suites",
    name2: "Home suitable for rent",
  },
  {
    name: "Student apartments",
    name2: "Student Home for rent",
  },
  {
    name: "Apartments for sale",
    name2: "Home suitable for sale",
  },
];
const items = [
  {
    img: "https://images.pexels.com/photos/425343/pexels-photo-425343.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    address: "Apartments for Rent",
  },
  {
    img: "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    address: "Houses for Rent",
  },
];

export {
  lessons,
  nearbyLocations,
  propertyFeatures,
  provinces,
  regions,
  items,
};
